// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdlRju6-2CrOkiR_dF7sd9nUPrHxdrk8',
    appId: '1:677724530633:web:1139b463bc3b741e222a18',
    messagingSenderId: '677724530633',
    projectId: 'attune-app-3ea44',
    authDomain: 'attune-app-3ea44.firebaseapp.com',
    storageBucket: 'attune-app-3ea44.firebasestorage.app',
    measurementId: 'G-VJYCW2QWJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclChe6TR5f5WfwZPw7zGBKjw_bizADwk',
    appId: '1:677724530633:android:16f2d2d0b132fded222a18',
    messagingSenderId: '677724530633',
    projectId: 'attune-app-3ea44',
    storageBucket: 'attune-app-3ea44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABn2IK8wrSksesnvAfweii0SuM0ymQ3Ng',
    appId: '1:677724530633:ios:e80e7a7077dcb60f222a18',
    messagingSenderId: '677724530633',
    projectId: 'attune-app-3ea44',
    storageBucket: 'attune-app-3ea44.firebasestorage.app',
    iosBundleId: 'com.example.attune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABn2IK8wrSksesnvAfweii0SuM0ymQ3Ng',
    appId: '1:677724530633:ios:e80e7a7077dcb60f222a18',
    messagingSenderId: '677724530633',
    projectId: 'attune-app-3ea44',
    storageBucket: 'attune-app-3ea44.firebasestorage.app',
    iosBundleId: 'com.example.attune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUdlRju6-2CrOkiR_dF7sd9nUPrHxdrk8',
    appId: '1:677724530633:web:ab10a5d3eae5d99d222a18',
    messagingSenderId: '677724530633',
    projectId: 'attune-app-3ea44',
    authDomain: 'attune-app-3ea44.firebaseapp.com',
    storageBucket: 'attune-app-3ea44.firebasestorage.app',
    measurementId: 'G-KL9JYQKH71',
  );
}
